spring:
    config:
        import: classpath:swagger.yml
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://lively-sea-5096.eu.auth0.com/

auth0:
    audience: https://takoya/login/car
